### ISSUE TITLE
Port Applications chooser from other plugs

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-parental-controls#37]
The way this application chooser is done, it will be affected by the issue mentioned here: https://elementaryos.stackexchange.com/questions/14929/add-startup-app-menu-broken

We should make this chooser match the one from Applications and Security & Privacy

**Comment by peteruithoven** [comment]
It's actually not, since it's scrollbar has a better policy, it's actually what I used in the end to fix the AppChooser in the Applications and Security plugs. 

![screenshot from 2018-02-28 13-11-29](https://user-images.githubusercontent.com/523210/36787057-09cb3e12-1c89-11e8-83a0-849b08c8d1f9.png)

But it is quite a shame there we have similar code in 3 different plugs. Isn't there a way to share this code? 
I can imagine it would be a bit to specific to add to Granite for example?

One issue is that it looks different, for comparison: 
![AppChooser in Applications plug](https://user-images.githubusercontent.com/523210/36781051-0f4fb05c-1c75-11e8-8653-a144b9e2e820.png)

**Comment by danrabbit** [comment]
I'm gonna close this since the approw has been abstracted here and the design matches other plugs
