### ISSUE TITLE
Rethink the name "Parental Controls"

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-parental-controls#45]
Just some thoughts, but I think "Parental Controls" might not be the best way to frame these tools because It only describes one type of relationship. I think that we can be a bit more inclusive here and I don't just mean in terms of "Parents and Guardians", but also in terms of other relationships like even between the user and themselves. For example, content restrictions could be useful for users who suffer from PTSD, not just for parents and children.

I think it might be more fitting to rename this section to something more inline with those concepts like "Digital Well-being" or "Screen Time" or something a bit more positive sounding than "Controls". I think our goal should be to give our users tools that empower them to develop a responsible and healthy relationship with their computer, not just a way to lock down and control them. This re-framing might help us to expand the way we think about these settings as well and might lead to new and interesting tools that we wouldn't have thought about in just the context of external control.

**Comment by cassidyjames** [comment]
"Digital Wellness" is another term I've heard around, possibly from Apple? I do like reframing it from "restrictions" to something more positive, so long as users still understand what it is/does.

**Comment by lewisgoddard** [comment]
Might these settings also be heavily used in an enterprise environment?

**Comment by danrabbit** [comment]
@lewisgoddard right so that's another concern is not infantilizing cases where you're administrating adults

**Comment by SixFingeredAmish** [comment]
I think "Usage Control" or "Content Control" would convey the functionality better while maintaining neutrality. "Digital Wellness" or "Digital Wellbeing" implies that the user is unwell.

**Comment by diazabdulm** [comment]
How about "Usage Management"? It leads the person to think they're in control.

**Comment by gjsman** [comment]
"Digital Wellbeing" is from Apple, and I think it describes it perfectly.

**Comment by cassidyjames** [comment]
@gjsman it's actually from Google with Android 9 Pie. Apple has called the concept "Digital Wellness" but it looks like the feature in the OS is called "Screen Time."

**Comment by SixFingeredAmish** [comment]
We definitely do not want to use Apple or Google’s names. They're probably trademarked anyway.

**Comment by bigtimmyc** [comment]
Safeguard, Digital Safeguard.... Bond, James Bond

**Comment by cassidyjames** [comment]
After attending the parental controls hackfest and thinking about this a lot more, I really do get why Apple went with "Screen Time" for the user-facing feature even though they call the concept "Digital Wellness". "Screen time" is a phrase I hear parents talking about for their kids quite a bit actually. But it also applies to people limiting themselves, too. I hear people say to "reduce screen time before bed to promote healthy sleep" and stuff like that. So as much as I'd hate being accused of copying that name… I get it :grimacing:

I don't _love_ anything including "Limits" because it can feel pretty negative. "Down time" could work but I think "screen time" is more common/directly associated in my experience. I guess something like "Screen Time & App Limits" _could_ be more clear maybe, and avoids sounding too negative? I don't know. It's hard because I don't really care to brand it with something clever, I mostly just want it to be as clear/obvious as possible from the System Settings screen.

**Comment by cassidyjames** [comment]
"Screen Time & Limits" sounds obvious and comprehensive enough to me. I've updated and reopened #92 to address that.
