### ISSUE TITLE
Allow placing restrictions on yourself

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-parental-controls#46]
In the spirit of digital wellbeing, we could allow the user to place certain restrictions on themself, i.e. if they wanted to restrict how much they use their computer.

**Comment by danrabbit** [comment]
This also implies removing this screen since you'll always have at least yourself to restrict:

![screenshot from 2018-08-09 16 44 47 2x](https://user-images.githubusercontent.com/7277719/43931514-98886e24-9bf3-11e8-94fa-d44825ba96e2.png)

**Comment by Dirli** [comment]
Fine, I have to limit myself. And I couldn’t deprive myself of administrator rights. I understood correctly, this is about administrators too?

**Comment by donadigo** [comment]
What I understand here is that:
* admininstrators can restrict anyone including themselves and
* standard users can only restrict themselves but they can authenticate as an admin to restrict others
(@danrabbit Correct?)

Things like #78 will require going into the daemon code & reworking it. I would like to get some things merged before that since the methods we currently use for restricting the user are not ideal.

**Comment by danrabbit** [comment]
@donadigo Yeah that sounds right to me
